name: Deploy to EC2
on:
  push:
    tags: 
      - 'v**'
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build the code
      run: |
        yarn install
        yarn run build

    - name: List files in runner's GitHub Actions workspace
      run: ls -la

    - name: Copy files to EC2 instance
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SERVER_CERT_KEY }} -r dist/* ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/ec2-user/apps/
